# Generated by Django 4.1.2 on 2022-11-17 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.ImageField(upload_to='photos')),
            ],
            options={
                'db_table': 'image',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'ingredient',
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure_amount_description', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'measurement',
            },
        ),
        migrations.CreateModel(
            name='Recipe_Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=50)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='recipe_pages.ingredient')),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='recipe_pages.measurement')),
            ],
            options={
                'db_table': 'recipe_ingredients',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_title', models.CharField(max_length=100)),
                ('preparation', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('author', models.CharField(blank=True, max_length=100)),
                ('link', models.SlugField(blank=True)),
                ('image', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='recipe_pages.image')),
            ],
            options={
                'db_table': 'recipe',
            },
        ),
        migrations.AddField(
            model_name='ingredient',
            name='measurement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='recipe_pages.measurement'),
        ),
    ]
