# Generated by Django 4.1.2 on 2022-11-17 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_pages', '0002_alter_recipe_image_alter_recipe_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='preparation',
            field=models.TextField(blank=True),
        ),
    ]
