# Generated by Django 4.1.2 on 2022-12-07 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_pages', '0003_alter_recipe_preparation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='link',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
